2021-01-31 03:06:03.414 | ERROR    | blue.user:delete_user:266 - 'list' object has no attribute 'id'
2021-01-31 03:13:49.424 | ERROR    | blue.user:delete_user:271 - (sqlite3.InterfaceError) Error binding parameter 0 - probably unsupported type.
[SQL: SELECT article.id AS article_id 
FROM article 
WHERE article.user_id = ?]
[parameters: (('6c625c586ce847c5a0e593b06e490e9e',),)]
(Background on this error at: http://sqlalche.me/e/13/rvf5)
2021-01-31 03:15:07.177 | ERROR    | blue.user:delete_user:272 - 'list' object has no attribute 'id'
2021-01-31 03:17:37.381 | ERROR    | blue.user:delete_user:272 - 'result' object has no attribute '__table__'
2021-01-31 04:04:12.846 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f07850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:05:12.805 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1040d5b80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:06:12.803 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1040e59d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:07:12.795 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10409dee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:08:12.794 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x104058dc0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:08:20.322 | ERROR    | blue.user:delete_user:275 - name 'article_id_list' is not defined
2021-01-31 04:09:12.792 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1040e5640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:10:12.796 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x102f91850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:11:12.803 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1040677c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:13:50.679 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1034a4610>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:14:50.644 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1035b8a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:15:50.644 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1035a46a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:16:50.644 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103519250>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:17:50.645 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1034a4670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:18:50.648 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1035a5520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:19:50.645 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10348fe80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:20:50.667 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1034943a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:21:50.672 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103494460>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:22:50.643 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103519d90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:23:50.649 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x10465c310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:24:50.649 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1035df640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:25:50.647 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1034f1e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2021-01-31 04:26:50.645 | ERROR    | schedule.article:get_site_new_article_msg:71 - https://lorexxar.cn/HTTPSConnectionPool(host='lorexxar.cn', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x103484160>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
